language: python
python:
  - "3.5"
  - "nightly"
install:
  - pip install -e .
script: python -m unittest
deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  skip_existing: true
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    tags: true
